# Generated by Django 4.2.1 on 2023-12-08 14:32

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_rubric_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='rubric', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpeg', 'png', 'jpg', 'bmp', 'tiff', 'ico', 'webp'))]),
            preserve_default=False,
        ),
    ]
