# Generated by Django 4.2.1 on 2023-12-08 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rubric_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='image',
            field=models.ImageField(blank=True, upload_to='rubric', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpeg', 'png', 'jpg', 'bmp', 'tiff', 'ico', 'webp'))]),
        ),
    ]
