# Generated by Django 4.2.1 on 2023-12-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_favoriteuserannouncements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=32, verbose_name='Описание'),
        ),
    ]
